### ISSUE TITLE
The 404 error is wrong as the link works for me

### ISSUE THREAD

**Issue by AfriadySafha** [enkidevs/curriculum#3097] opened 2022-07-31 23:34 UTC
The 404 error is wrong as the link works for me

_Originally posted by @Stefan-Stojanovic in https://github.com/enkidevs/curriculum/pull/3091#issuecomment-1153907254_

**Comment by nem035** [comment] 2022-08-01 15:25
Hi Afriady, I'm closing this issue as I'm unsure what the problem is but feel free to reopen it if/when you update the description.

**Closed by nem035** 2022-08-01 15:25 UTC
